apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8sbackup
spec:
  schedule: "17 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          serviceAccountName: k8sbackup
          restartPolicy: Never
          containers:
            - name: k8sbackup
              image: ghcr.io/alexanderthaller/k8sbackup-rs:0.1.1
              imagePullPolicy: IfNotPresent
              args:
                - --backup-type
                - restic
              envFrom:
                - secretRef:
                    name: k8sbackup-restic
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
              volumeMounts:
                - name: tmp
                  mountPath: /tmp
          volumes:
            - name: tmp
              emptyDir: {}
